# Generated by Django 5.1.3 on 2024-12-08 09:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('company', models.CharField(max_length=100)),
                ('birth_year', models.IntegerField()),
                ('gender', models.CharField(choices=[('male', '男性'), ('female', '女性')], max_length=10)),
                ('department', models.CharField(choices=[('sales', '営業部'), ('planning', '企画部'), ('general_affairs', '総務部'), ('hr', '人事部'), ('manufacturing', '製造部'), ('development', '開発部')], max_length=50)),
                ('joining_year', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='PartyPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender_restriction', models.CharField(choices=[('same_gender', '同性'), ('no_restriction', '希望なし')], max_length=50)),
                ('age_restriction', models.CharField(choices=[('same_age', '同年代'), ('broad_age', '幅広い年代'), ('no_restriction', '希望なし')], max_length=50)),
                ('joining_year_restriction', models.CharField(choices=[('exact_match', '完全一致'), ('no_restriction', '希望なし')], max_length=50)),
                ('department_restriction', models.CharField(choices=[('same_department', '所属部署内希望'), ('mixed_departments', '他部署混在'), ('no_restriction', '希望なし')], max_length=50)),
                ('atmosphere_preference', models.CharField(choices=[('quiet', '落ち着いたお店'), ('lively', 'わいわいできるお店'), ('no_restriction', '希望なし')], max_length=50)),
                ('desired_date', models.DateField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.user')),
            ],
        ),
    ]
