# Generated by Django 5.1.4 on 2024-12-15 14:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("company", models.CharField(max_length=100)),
                ("birth_year", models.IntegerField()),
                (
                    "gender",
                    models.CharField(
                        choices=[("male", "男性"), ("female", "女性")], max_length=10
                    ),
                ),
                (
                    "department",
                    models.CharField(
                        choices=[
                            ("sales", "営業部"),
                            ("planning", "企画部"),
                            ("general_affairs", "総務部"),
                            ("hr", "人事部"),
                            ("manufacturing", "製造部"),
                            ("development", "開発部"),
                        ],
                        max_length=50,
                    ),
                ),
                ("joining_year", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=50)),
                ("full_name", models.CharField(max_length=100)),
                ("furigana", models.CharField(max_length=100)),
                (
                    "gender",
                    models.CharField(
                        choices=[("male", "男性"), ("female", "女性")], max_length=10
                    ),
                ),
                ("birth_year", models.IntegerField()),
                ("join_year", models.IntegerField()),
                ("department", models.CharField(max_length=50)),
                ("station", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="Participation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "gender_restriction",
                    models.CharField(
                        choices=[
                            ("same_gender", "同性"),
                            ("no_restriction", "希望なし"),
                        ],
                        default="no_restriction",
                        max_length=50,
                    ),
                ),
                (
                    "age_restriction",
                    models.CharField(
                        choices=[
                            ("same_age", "同年代"),
                            ("broad_age", "幅広い年代"),
                            ("no_restriction", "希望なし"),
                        ],
                        default="no_restriction",
                        max_length=50,
                    ),
                ),
                (
                    "joining_year_restriction",
                    models.CharField(
                        choices=[
                            ("exact_match", "同期のみ"),
                            ("no_restriction", "希望なし"),
                        ],
                        default="no_restriction",
                        max_length=50,
                    ),
                ),
                (
                    "department_restriction",
                    models.CharField(
                        choices=[
                            ("same_department", "所属部署内希望"),
                            ("mixed_departments", "他部署混在"),
                            ("no_restriction", "希望なし"),
                        ],
                        default="no_restriction",
                        max_length=50,
                    ),
                ),
                (
                    "atmosphere_preference",
                    models.CharField(
                        choices=[
                            ("quiet", "落ち着いたお店"),
                            ("lively", "わいわいできるお店"),
                            ("no_restriction", "希望なし"),
                        ],
                        default="no_restriction",
                        max_length=50,
                    ),
                ),
                ("desired_dates", models.JSONField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="participations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PartyPreference",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "gender_restriction",
                    models.CharField(
                        choices=[
                            ("same_gender", "同性"),
                            ("no_restriction", "希望なし"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "age_restriction",
                    models.CharField(
                        choices=[
                            ("same_age", "同年代"),
                            ("broad_age", "幅広い年代"),
                            ("no_restriction", "希望なし"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "joining_year_restriction",
                    models.CharField(
                        choices=[
                            ("exact_match", "完全一致"),
                            ("no_restriction", "希望なし"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "department_restriction",
                    models.CharField(
                        choices=[
                            ("same_department", "所属部署内希望"),
                            ("mixed_departments", "他部署混在"),
                            ("no_restriction", "希望なし"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "atmosphere_preference",
                    models.CharField(
                        choices=[
                            ("quiet", "落ち着いたお店"),
                            ("lively", "わいわいできるお店"),
                            ("no_restriction", "希望なし"),
                        ],
                        max_length=50,
                    ),
                ),
                ("desired_date", models.DateField()),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.user"
                    ),
                ),
            ],
        ),
    ]
