# Generated by Django 5.1.3 on 2024-12-08 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_participation"),
    ]

    operations = [
        migrations.AlterField(
            model_name="participation",
            name="joining_year_restriction",
            field=models.CharField(
                choices=[("exact_match", "同期のみ"), ("no_restriction", "希望なし")],
                default="no_restriction",
                max_length=50,
            ),
        ),
    ]