# Generated by Django 5.1.3 on 2025-01-01 23:48

import uuid
from django.db import migrations, models


def generate_unique_identifiers(apps, schema_editor):
    Group = apps.get_model("api", "Group")
    for group in Group.objects.all():
        group.identifier = str(uuid.uuid4())  # 一意のUUIDを設定
        group.save()


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_restaurant"),
    ]

    operations = [
        # "name" フィールドの削除
        migrations.RemoveField(
            model_name="group",
            name="name",
        ),
        # "identifier" フィールドの追加 (一時的に null を許容)
        migrations.AddField(
            model_name="group",
            name="identifier",
            field=models.CharField(
                default=None, editable=False, max_length=36, unique=True, null=True
            ),
        ),
        # 既存データに一意の識別子を割り当て
        migrations.RunPython(generate_unique_identifiers),
        # "identifier" フィールドから null を禁止
        migrations.AlterField(
            model_name="group",
            name="identifier",
            field=models.CharField(
                default=uuid.uuid4, editable=False, max_length=36, unique=True
            ),
        ),
        # レストランモデルに "is_selected" フィールドを追加
        migrations.AddField(
            model_name="restaurant",
            name="is_selected",
            field=models.BooleanField(default=False),
        ),
    ]
