# Generated by Django 5.1.3 on 2025-01-05 03:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_remove_group_name_group_identifier_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="PartyPreference",
        ),
        migrations.DeleteModel(
            name="User",
        ),
    ]
