# Generated by Django 5.1.4 on 2024-12-28 02:23

import datetime
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_notification"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userprofile",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="updated_at",
        ),
        migrations.AlterField(
            model_name="participation",
            name="desired_dates",
            field=models.JSONField(
                validators=[
                    django.core.validators.MinValueValidator(
                        datetime.date(2024, 12, 28)
                    )
                ]
            ),
        ),
        migrations.AlterField(
            model_name="participation",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="participations",
                to="api.userprofile",
            ),
        ),
    ]
