# Generated by Django 5.1.3 on 2024-12-18 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_alter_participation_joining_year_restriction"),
        ("api", "0004_remove_participation_date_remove_participation_time"),
    ]

    operations = []
